/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Principal;

import Habana.Habana;
import Habana.Habanaform;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author jlizquierdo
 * Clase Principal de la aplicación, con menú, tool bar y fondo de pantalla
 */
public class Principal extends javax.swing.JFrame {

    javax.swing.JLabel backgroundLabel;
    java.awt.Image imageFondo ;
    Habana habana;
    
    /**
     * Crea el formulario principal
     */
    public Principal() {
        initComponents();
        // cargo el objeto habana, para tener guardadas las reservas en toda la aplicacion
        this.habana = new Habana();
        // Después de initComponents()
        // icono
        ImageIcon icon = new ImageIcon(getClass().getResource("/img/hotel.png")); // Reemplaza con la ruta correcta
        this.setIconImage(icon.getImage());        
        // imagen de fondo
        this.PanelHabana.setOpaque(false);
        this.imageFondo = new javax.swing.ImageIcon(getClass().getResource("/img/fondo_hotel.jpg")).getImage();        
        this.posFondo();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelHabana = new javax.swing.JPanel();
        toolHabana = new javax.swing.JToolBar();
        btnHabana = new javax.swing.JButton();
        MenuHabana = new javax.swing.JMenuBar();
        Menu1 = new javax.swing.JMenu();
        Menu11 = new javax.swing.JMenuItem();
        Menu12 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Aplicación Hotel");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setLocationByPlatform(true);
        setName("Principal"); // NOI18N
        setPreferredSize(new java.awt.Dimension(800, 600));
        setSize(new java.awt.Dimension(0, 0));

        PanelHabana.setName("HotelHabana"); // NOI18N
        PanelHabana.setOpaque(false);
        PanelHabana.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                PanelHabanaComponentResized(evt);
            }
        });
        PanelHabana.setLayout(new java.awt.BorderLayout());
        getContentPane().add(PanelHabana, java.awt.BorderLayout.CENTER);
        PanelHabana.getAccessibleContext().setAccessibleName("PanelPrincipal");
        PanelHabana.getAccessibleContext().setAccessibleDescription("PanelPrincipal");

        toolHabana.setRollover(true);

        btnHabana.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        btnHabana.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/hotel.png"))); // NOI18N
        btnHabana.setText("Salón Habana");
        btnHabana.setToolTipText("Pulse para acceder a las reservas del salón Habana");
        btnHabana.setActionCommand("habana");
        btnHabana.setFocusable(false);
        btnHabana.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnHabana.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHabanaActionPerformed(evt);
            }
        });
        toolHabana.add(btnHabana);

        getContentPane().add(toolHabana, java.awt.BorderLayout.PAGE_START);

        MenuHabana.setToolTipText("Opciones del Menú Principal");
        MenuHabana.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        MenuHabana.setName("MenuPrincipal"); // NOI18N

        Menu1.setText("Principal");

        Menu11.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_H, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        Menu11.setText("Salón Habana");
        Menu11.setName("Menu1"); // NOI18N
        Menu11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Menu11ActionPerformed(evt);
            }
        });
        Menu1.add(Menu11);
        Menu11.getAccessibleContext().setAccessibleDescription("Reservas en el Salón Habana");

        Menu12.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        Menu12.setText("Salir");
        Menu12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Menu12ActionPerformed(evt);
            }
        });
        Menu1.add(Menu12);

        MenuHabana.add(Menu1);
        Menu1.getAccessibleContext().setAccessibleName("Opciones");

        setJMenuBar(MenuHabana);
        MenuHabana.getAccessibleContext().setAccessibleName("MenuPrincpal");

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Posiciona la imagen de fondo en el panel, para que cada vez que se dimensiona el frame se posicione y redimensione 
    */
    private void posFondo()
    {
        this.imageFondo = this.imageFondo.getScaledInstance(this.PanelHabana.getWidth(), this.PanelHabana.getHeight(), java.awt.Image.SCALE_SMOOTH);
        this.backgroundLabel = new javax.swing.JLabel(new javax.swing.ImageIcon(imageFondo));        
        this.PanelHabana.removeAll();
        this.PanelHabana.add(this.backgroundLabel);
        this.backgroundLabel.setBounds(0, 0, this.PanelHabana.getWidth(), this.PanelHabana.getHeight());        
    }
    
    private void btnHabanaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHabanaActionPerformed
        // TODO add your handling code here:
        Habanaform dialogo = new Habanaform(this,true,this.habana);
        dialogo.setVisible(true);
    }//GEN-LAST:event_btnHabanaActionPerformed

    private void PanelHabanaComponentResized(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_PanelHabanaComponentResized
        // TODO add your handling code here:
        this.posFondo();
    }//GEN-LAST:event_PanelHabanaComponentResized

    private void Menu11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Menu11ActionPerformed
        // TODO add your handling code here:
       this.btnHabanaActionPerformed(evt);
    }//GEN-LAST:event_Menu11ActionPerformed

    private void Menu12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Menu12ActionPerformed
        // TODO add your handling code here:
        this.salir();
    }//GEN-LAST:event_Menu12ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }
    
    /**
     * Método para controlar la salida de la aplicación
     */
    private void salir()
    {
            int opcion = JOptionPane.showOptionDialog(
                this,                     // Componente padre (en este caso, nulo para un diálogo independiente)
                "¿Seguro de salir de la aplicación?",   // Mensaje a mostrar
                "Salir de la Aplicación",          // Título del cuadro de diálogo
                JOptionPane.YES_NO_OPTION,// Tipo de opciones (Sí y No)
                JOptionPane.QUESTION_MESSAGE, // Tipo de icono
                null,                     // Icono personalizado (en este caso, nulo)
                new Object[]{"Sí", "No"}, // Opciones personalizadas
                "No");                    // Opción por defecto
            if ( opcion == JOptionPane.YES_OPTION )
                System.exit(0);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu Menu1;
    private javax.swing.JMenuItem Menu11;
    private javax.swing.JMenuItem Menu12;
    private javax.swing.JMenuBar MenuHabana;
    private javax.swing.JPanel PanelHabana;
    private javax.swing.JButton btnHabana;
    private javax.swing.JToolBar toolHabana;
    // End of variables declaration//GEN-END:variables
}
