/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Principal;

import Habana.Habanaform;
import java.awt.Image;
import javax.swing.ImageIcon;

/**
 *
 * @author jlizquierdo
 */
public class Principal extends javax.swing.JFrame {

    javax.swing.JLabel backgroundLabel;
    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
        // Después de initComponents()
        // icono
        ImageIcon icon = new ImageIcon(getClass().getResource("/img/hotel.png")); // Reemplaza con la ruta correcta
        this.setIconImage(icon.getImage());        
        // imagen de fondo
        java.awt.Image image = new javax.swing.ImageIcon(getClass().getResource("/img/fondo_hotel.jpg")).getImage();
        image = image.getScaledInstance(this.Panel1.getWidth(), this.Panel1.getHeight(), java.awt.Image.SCALE_SMOOTH);
        this.backgroundLabel = new javax.swing.JLabel(new javax.swing.ImageIcon(image));
        this.Panel1.setOpaque(false);
        this.Panel1.add(backgroundLabel);
        backgroundLabel.setBounds(0, 0, this.Panel1.getWidth(), this.Panel1.getHeight());        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Panel1 = new javax.swing.JPanel();
        toolHabana = new javax.swing.JToolBar();
        btnHabana = new javax.swing.JButton();
        MenuHabana = new javax.swing.JMenuBar();
        Menu1 = new javax.swing.JMenu();
        Menu11 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Aplicación Hotel");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setLocationByPlatform(true);
        setName("Principal"); // NOI18N
        setPreferredSize(new java.awt.Dimension(800, 600));
        setSize(new java.awt.Dimension(0, 0));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        Panel1.setName("Hotel Cuba"); // NOI18N
        Panel1.setOpaque(false);
        Panel1.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                Panel1ComponentResized(evt);
            }
        });

        javax.swing.GroupLayout Panel1Layout = new javax.swing.GroupLayout(Panel1);
        Panel1.setLayout(Panel1Layout);
        Panel1Layout.setHorizontalGroup(
            Panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 530, Short.MAX_VALUE)
        );
        Panel1Layout.setVerticalGroup(
            Panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 299, Short.MAX_VALUE)
        );

        getContentPane().add(Panel1, java.awt.BorderLayout.CENTER);
        Panel1.getAccessibleContext().setAccessibleName("PanelPrincipal");
        Panel1.getAccessibleContext().setAccessibleDescription("PanelPrincipal");

        toolHabana.setRollover(true);

        btnHabana.setText("Salón Habana");
        btnHabana.setActionCommand("habana");
        btnHabana.setFocusable(false);
        btnHabana.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnHabana.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnHabana.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHabanaActionPerformed(evt);
            }
        });
        toolHabana.add(btnHabana);

        getContentPane().add(toolHabana, java.awt.BorderLayout.PAGE_START);

        MenuHabana.setToolTipText("Opciones del Menú Principal");
        MenuHabana.setName("MenuPrincipal"); // NOI18N

        Menu1.setText("Principal");

        Menu11.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_H, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        Menu11.setText("Salón Habana");
        Menu11.setName("Menu1"); // NOI18N
        Menu11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Menu11ActionPerformed(evt);
            }
        });
        Menu1.add(Menu11);
        Menu11.getAccessibleContext().setAccessibleDescription("Reservas en el Salón Habana");

        MenuHabana.add(Menu1);
        Menu1.getAccessibleContext().setAccessibleName("Opciones");

        setJMenuBar(MenuHabana);
        MenuHabana.getAccessibleContext().setAccessibleName("MenuPrincpal");

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
  
    }//GEN-LAST:event_formWindowActivated

    private void btnHabanaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHabanaActionPerformed
        // TODO add your handling code here:
        Habanaform dialogo = new Habanaform(this,true);
        dialogo.setVisible(true);
    }//GEN-LAST:event_btnHabanaActionPerformed

    private void Panel1ComponentResized(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_Panel1ComponentResized
        // TODO add your handling code here:
        this.backgroundLabel.setBounds(0, 0, this.Panel1.getWidth(), this.Panel1.getHeight());        
    }//GEN-LAST:event_Panel1ComponentResized

    private void Menu11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Menu11ActionPerformed
        // TODO add your handling code here:
       this.btnHabanaActionPerformed(evt);
    }//GEN-LAST:event_Menu11ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu Menu1;
    private javax.swing.JMenuItem Menu11;
    private javax.swing.JMenuBar MenuHabana;
    private javax.swing.JPanel Panel1;
    private javax.swing.JButton btnHabana;
    private javax.swing.JToolBar toolHabana;
    // End of variables declaration//GEN-END:variables
}
