/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package Habana;

import javax.swing.table.DefaultTableModel;

/**
 *
 * @author jlizquierdo
 */
public class Habanaform extends javax.swing.JDialog {

    /**
     * Creates new form Habana
     */
    Habana habana; // atributo objeto para controlar el formulario
    
    public Habanaform(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        this.habana = new Habana();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelHabana = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableReservas = new javax.swing.JTable();
        toolHabana = new javax.swing.JToolBar();
        nuevaReserva = new javax.swing.JButton();
        editaReserva = new javax.swing.JButton();
        borraReserva = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setName("HabanaDlg"); // NOI18N
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        PanelHabana.setName("PanelHabana"); // NOI18N

        tableReservas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Fecha", "Contacto", "Teléfono"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableReservas.setToolTipText("Detalle de las reservas");
        tableReservas.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane2.setViewportView(tableReservas);

        javax.swing.GroupLayout PanelHabanaLayout = new javax.swing.GroupLayout(PanelHabana);
        PanelHabana.setLayout(PanelHabanaLayout);
        PanelHabanaLayout.setHorizontalGroup(
            PanelHabanaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelHabanaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 482, Short.MAX_VALUE))
        );
        PanelHabanaLayout.setVerticalGroup(
            PanelHabanaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelHabanaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        toolHabana.setRollover(true);

        nuevaReserva.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/anadir.png"))); // NOI18N
        nuevaReserva.setText("Añadir");
        nuevaReserva.setToolTipText("Añade una nueva reserva");
        nuevaReserva.setFocusable(false);
        nuevaReserva.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        nuevaReserva.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        nuevaReserva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nuevaReservaActionPerformed(evt);
            }
        });
        toolHabana.add(nuevaReserva);

        editaReserva.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/editar.png"))); // NOI18N
        editaReserva.setText("Editar");
        editaReserva.setToolTipText("Modifica la reserva seleccionada");
        editaReserva.setFocusable(false);
        editaReserva.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        editaReserva.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        editaReserva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editaReservaActionPerformed(evt);
            }
        });
        toolHabana.add(editaReserva);

        borraReserva.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/borrar.png"))); // NOI18N
        borraReserva.setText("Borrar");
        borraReserva.setToolTipText("Borra la reserva seleccionada");
        borraReserva.setFocusable(false);
        borraReserva.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        borraReserva.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        toolHabana.add(borraReserva);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(PanelHabana, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(toolHabana, javax.swing.GroupLayout.PREFERRED_SIZE, 474, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(toolHabana, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PanelHabana, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        PanelHabana.getAccessibleContext().setAccessibleName("Panel Habana");

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
       // cargamos un objeto habana para almacenar las reservas
       // aqui cargaríamos las reservas si por ejemplo las cogieramos de un fichero
       this.recargaTablaReservas(this.getHabana());
    }//GEN-LAST:event_formWindowOpened

    private void nuevaReservaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nuevaReservaActionPerformed
        // TODO add your handling code here:
        ReservaHabanaForm dialogo = new ReservaHabanaForm(this, true, this.getHabana(), 1, 0);
        dialogo.setVisible(true);
        this.recargaTablaReservas(this.getHabana());
    }//GEN-LAST:event_nuevaReservaActionPerformed

    private void editaReservaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editaReservaActionPerformed
        int seleccion = this.tableReservas.getSelectedRow();
        ReservaHabanaForm dialogo = new ReservaHabanaForm(this, true, this.getHabana(), 2, seleccion );
        dialogo.setVisible(true);
        this.recargaTablaReservas(this.getHabana());
    }//GEN-LAST:event_editaReservaActionPerformed

    private Habana getHabana() {
        return habana;
    }

    private void setHabana(Habana habana) {
        this.habana = habana;
    }
    
    protected void recargaTablaReservas( Habana habana )
    {  
        
        // Obtener el modelo de la tabla
        DefaultTableModel modelo = (DefaultTableModel) this.tableReservas.getModel();
        // Limpiar el modelo (si es necesario)
        modelo.setRowCount(0);
        // Recorrer el ArrayList y agregar cada objeto como una fila en el modelo
        for (ReservaHabana reserva : this.habana.getReservas() ) {
            modelo.addRow(new Object[]{ reserva.getFecha().toString().substring(0, 10), reserva.getNombre(), reserva.getTelefono()});
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelHabana;
    private javax.swing.JButton borraReserva;
    private javax.swing.JButton editaReserva;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton nuevaReserva;
    private javax.swing.JTable tableReservas;
    private javax.swing.JToolBar toolHabana;
    // End of variables declaration//GEN-END:variables
}
