/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package Habana;

import java.util.Date;
import javax.swing.JSpinner;

/**
 *
 * @author jlizquierdo
 */
public class ReservaHabanaForm extends javax.swing.JDialog {

    int modo; // modo de dialogo, 1 añadir 2 editar
    int seleccion; // registro seleccionado de la tabla
    Habana habana; // objeto principal donde se guardan las reservas

    /**
     * Creates new form ReservaHabanaForm
     * @param parent
     * @param habana Objeto principal donde se guardan las reservas
     * @param modo 1 añadir, 2 editar
     * @param seleccion Registro seleccionado de la tabla
     */
    public ReservaHabanaForm(java.awt.Dialog parent, boolean modal, Habana habana, int modo, int seleccion ) {
        super(parent, modal);
        initComponents();
        this.modo = modo;
        this.seleccion = seleccion;
        this.habana = habana;
    }
    

    public int getModo() {
        return modo;
    }

    public void setModo(int modo) {
        this.modo = modo;
    }

    public int getSeleccion() {
        return seleccion;
    }

    public void setSeleccion(int seleccion) {
        this.seleccion = modo;
    }
    
    public Habana getHabana() {
        return habana;
    }

    public void setHabana(Habana habana) {
        this.habana = habana;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grpRestaurante = new javax.swing.ButtonGroup();
        panelForm = new javax.swing.JPanel();
        labelContacto = new javax.swing.JLabel();
        textContacto = new javax.swing.JTextField();
        labelTelefono = new javax.swing.JLabel();
        textTelefono = new javax.swing.JTextField();
        comTipo = new javax.swing.JComboBox<>();
        labelTipo = new javax.swing.JLabel();
        labelPersonas = new javax.swing.JLabel();
        spiPersonas = new javax.swing.JSpinner();
        spiFecha = new javax.swing.JSpinner();
        labelFecha = new javax.swing.JLabel();
        LabelJornadas = new javax.swing.JLabel();
        spiJornadas = new javax.swing.JSpinner();
        chkHabitaciones = new javax.swing.JCheckBox();
        panelRestaurante = new javax.swing.JPanel();
        radBufe = new javax.swing.JRadioButton();
        radCarta = new javax.swing.JRadioButton();
        radChef = new javax.swing.JRadioButton();
        radNoRest = new javax.swing.JRadioButton();
        panelBtn = new javax.swing.JPanel();
        btnCancelar = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setModal(true);
        setName("dlgFormReserva"); // NOI18N
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        java.awt.FlowLayout flowLayout1 = new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 1, 1);
        flowLayout1.setAlignOnBaseline(true);
        getContentPane().setLayout(flowLayout1);

        panelForm.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos de la Reserva"));
        panelForm.setName(""); // NOI18N

        labelContacto.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        labelContacto.setText("Contacto:");

        textContacto.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        textContacto.setToolTipText("Introduzca la persona de contacto");

        labelTelefono.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        labelTelefono.setText("Teléfono:");

        textTelefono.setToolTipText("Introduzca el teléfono de contacto");

        comTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Banquete", "Jornada", "Congreso" }));
        comTipo.setToolTipText("Seleccione el tipo de reserva");
        comTipo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                comTipoItemStateChanged(evt);
            }
        });

        labelTipo.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        labelTipo.setText("Tipo:");

        labelPersonas.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        labelPersonas.setText("Personas:");

        spiPersonas.setModel(new javax.swing.SpinnerNumberModel(1, null, 80, 1));
        spiPersonas.setToolTipText("Introduzca el número de Jornadas");
        spiPersonas.setName("spiPersonas"); // NOI18N

        spiFecha.setModel(new javax.swing.SpinnerDateModel());
        spiFecha.setToolTipText("Fecha de la Reserva");
        spiFecha.setName("spiFecha"); // NOI18N

        labelFecha.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        labelFecha.setText("Fecha:");

        LabelJornadas.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        LabelJornadas.setText("Jornadas:");

        spiJornadas.setToolTipText("Introduzca el número de Jornadas");

        chkHabitaciones.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        chkHabitaciones.setText("Requiere Habitaciones");
        chkHabitaciones.setToolTipText("Indique si requiere habitaciones");

        panelRestaurante.setBorder(javax.swing.BorderFactory.createTitledBorder("Servicio de Restaurante"));

        grpRestaurante.add(radBufe);
        radBufe.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        radBufe.setText("Bufé");
        radBufe.setToolTipText("Pulse para seleccionar bufé");
        panelRestaurante.add(radBufe);

        grpRestaurante.add(radCarta);
        radCarta.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        radCarta.setText("Carta");
        radCarta.setToolTipText("Pulse para seleccionar carta");
        panelRestaurante.add(radCarta);

        grpRestaurante.add(radChef);
        radChef.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        radChef.setText("Chef");
        radChef.setToolTipText("Pulse para seleccionar chef");
        panelRestaurante.add(radChef);

        grpRestaurante.add(radNoRest);
        radNoRest.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        radNoRest.setText("No Precisa");
        radNoRest.setToolTipText("Pulse si no precisa servicio de restaurante");
        panelRestaurante.add(radNoRest);

        javax.swing.GroupLayout panelFormLayout = new javax.swing.GroupLayout(panelForm);
        panelForm.setLayout(panelFormLayout);
        panelFormLayout.setHorizontalGroup(
            panelFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelFormLayout.createSequentialGroup()
                    .addGap(8, 8, 8)
                    .addComponent(LabelJornadas, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(spiJornadas, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(chkHabitaciones, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap())
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelFormLayout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelRestaurante, javax.swing.GroupLayout.PREFERRED_SIZE, 451, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGroup(panelFormLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(panelFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelFormLayout.createSequentialGroup()
                        .addComponent(labelFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(spiFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelFormLayout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addComponent(textContacto, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(labelContacto, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelFormLayout.createSequentialGroup()
                        .addComponent(labelTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(textTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelFormLayout.createSequentialGroup()
                        .addGroup(panelFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelTipo)
                            .addComponent(labelPersonas))
                        .addGap(31, 31, 31)
                        .addGroup(panelFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(spiPersonas, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(comTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))))
        );
        panelFormLayout.setVerticalGroup(
            panelFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFormLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(panelFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(labelFecha, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(spiFecha))
                .addGap(10, 10, 10)
                .addGroup(panelFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(textContacto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelContacto, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(panelFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(panelFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelTipo)
                    .addComponent(comTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(panelFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(labelPersonas)
                    .addComponent(spiPersonas, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(panelRestaurante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelFormLayout.createSequentialGroup()
                        .addGroup(panelFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(spiJornadas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(chkHabitaciones))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(LabelJornadas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        getContentPane().add(panelForm);

        panelBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        panelBtn.setPreferredSize(new java.awt.Dimension(300, 100));
        panelBtn.setLayout(new java.awt.GridBagLayout());

        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cancelar.png"))); // NOI18N
        btnCancelar.setText("Cancelar");
        btnCancelar.setToolTipText("Pulse para cancelar las modificaciones de la freserva actual");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        panelBtn.add(btnCancelar, new java.awt.GridBagConstraints());

        btnGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/guardar.png"))); // NOI18N
        btnGuardar.setText("Guardar");
        btnGuardar.setToolTipText("Pulse para guardar la reserva");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        panelBtn.add(btnGuardar, new java.awt.GridBagConstraints());

        getContentPane().add(panelBtn);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        JSpinner.DateEditor dateEditor = new JSpinner.DateEditor(this.spiFecha, "dd/MM/yyyy"); // Puedes cambiar el formato según tus preferencias
        this.spiFecha.setEditor(dateEditor);     
        this.LabelJornadas.setVisible(false);
        this.spiJornadas.setVisible(false);
        this.chkHabitaciones.setVisible(false);
        this.radNoRest.setSelected(true);
        if ( this.getModo()==1 ) // añadir, asignamos los valores por defecto
        {
           this.spiFecha.setValue(new Date());
           this.radNoRest.setSelected(true);
           this.textContacto.requestFocus();
        }
        else if( this.getModo()==2 ) // editar
        {
            // editar cargamos el objeto guardado en el array list y asignamos sus datos
            this.textContacto.setText(this.getHabana().getReservas().get(seleccion).getNombre());
            this.textTelefono.setText(this.getHabana().getReservas().get(seleccion).getTelefono());
            this.comTipo.setSelectedIndex(this.getHabana().getReservas().get(seleccion).getTipo());
            this.spiPersonas.setValue(this.getHabana().getReservas().get(seleccion).getPersonas());
            switch (this.getHabana().getReservas().get(seleccion).getCocina())
            {
                case 'B':
                    this.radBufe.setSelected(true);
                    break;
                case 'C':
                    this.radCarta.setSelected(true);
                    break;
                case 'F':
                    this.radChef.setSelected(true);
                    break;
                case 'N':
                    this.radNoRest.setSelected(true);
                    break;
            }
            this.spiJornadas.setValue(this.getHabana().getReservas().get(seleccion).getDias());
            if( this.getHabana().getReservas().get(seleccion).getHabitaciones())
              this.chkHabitaciones.setSelected(true);
            this.textContacto.requestFocus();
        }
    }//GEN-LAST:event_formWindowOpened

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void comTipoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_comTipoItemStateChanged
        // TODO add your handling code here:
        boolean visible = this.comTipo.getSelectedIndex() == 2; // seleccionado congreso
        this.LabelJornadas.setVisible(visible);
        this.spiJornadas.setVisible(visible);
        this.chkHabitaciones.setVisible(visible);
    }//GEN-LAST:event_comTipoItemStateChanged

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        // TODO add your handling code here:
        ReservaHabana reserva = new ReservaHabana();
        if ( this.getModo() == 2 ) // editamos, tomamos el valor del objeto pasado
        {
            reserva = this.getHabana().getReservas().get(seleccion);
        }
        reserva.setFecha((Date) this.spiFecha.getValue());
        reserva.setNombre(this.textContacto.getText());
        reserva.setTelefono(this.textTelefono.getText());
        reserva.setTipo(this.comTipo.getSelectedIndex());
        reserva.setPersonas((int) this.spiPersonas.getValue() );
        if(this.radBufe.isSelected())
            reserva.setCocina('B');
        else if ( this.radCarta.isSelected())
            reserva.setCocina('C');
        else if ( this.radChef.isSelected())
            reserva.setCocina('F');
        else if ( this.radNoRest.isSelected())
            reserva.setCocina('N');
        if ( this.comTipo.getSelectedIndex()!=2 )
        {
            reserva.setDias(0);
            reserva.setHabitaciones(false);
        }else{
            reserva.setDias((int) this.spiJornadas.getValue() );
            reserva.setHabitaciones(this.chkHabitaciones.isSelected());
        }
        if ( this.getModo() == 1 ) // aqui simplemente la añadimos a las reservas
            this.getHabana().addReserva(reserva);
        this.setVisible(false);
    }//GEN-LAST:event_btnGuardarActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LabelJornadas;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JCheckBox chkHabitaciones;
    private javax.swing.JComboBox<String> comTipo;
    private javax.swing.ButtonGroup grpRestaurante;
    private javax.swing.JLabel labelContacto;
    private javax.swing.JLabel labelFecha;
    private javax.swing.JLabel labelPersonas;
    private javax.swing.JLabel labelTelefono;
    private javax.swing.JLabel labelTipo;
    private javax.swing.JPanel panelBtn;
    private javax.swing.JPanel panelForm;
    private javax.swing.JPanel panelRestaurante;
    private javax.swing.JRadioButton radBufe;
    private javax.swing.JRadioButton radCarta;
    private javax.swing.JRadioButton radChef;
    private javax.swing.JRadioButton radNoRest;
    private javax.swing.JSpinner spiFecha;
    private javax.swing.JSpinner spiJornadas;
    private javax.swing.JSpinner spiPersonas;
    private javax.swing.JTextField textContacto;
    private javax.swing.JTextField textTelefono;
    // End of variables declaration//GEN-END:variables
}
